FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl openssl

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run prisma:generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
